### ISSUE TITLE
How to create a dotted QR Code

### ISSUE THREAD

**Issue by asigamba** [alexzhirkevich/custom-qr-generator-flutter#2]
Is it possible to create a dotted QR Code with this lib like this?
![image](https://user-images.githubusercontent.com/120511208/207428227-fc67ef84-9aee-442b-af4e-96001d1a8efb.png)

**Comment by alexzhirkevich** [comment]
You can make pixels round and blue like that:

```dart
options: QrOptions(
    shapes: QrShapes(
        darkPixel: QrPixelShape.circle(),
    ),
    colors: QrColors(
        dark: QrColor.solid(Colors.blue)
    )
)
```

QR code shape will be supported in future versions

**Comment by asigamba** [comment]
wow. to be honest, this is the best qr code generator package for flutter. it is already much more powerful than other packages.
the only reason why it is not yet as visible as other packages is probably that it is new or using the wrong tags. ( i dont know)
if one can add icons and change the shape. this will be the final game changer.

**Comment by alexzhirkevich** [comment]
You can add icon just by placing image on top of qr code and increasing error correction level (ecl) in options. It will work

**Comment by zogol** [comment]
the library is great. with the custom shape qr code feature all qr dreams come true.
I want to create something like this.

![image](https://user-images.githubusercontent.com/100768486/208265896-cd1fdfc9-cccc-4a77-9d35-9c43a23adbce.png)

**Comment by asigamba** [comment]
> Thanks, @asigamba.
> 
> You can add icon just by placing image on top of qr code and increasing error correction level (ecl) in options. It will work

thank youuu
